a=input("Enter a name followed by the date of birth:")
e=input("Enter a name followed by the date of birth:")
b=input("Enter a name followed by the date of birth:")
c=input("Enter a name followed by the date of birth:")
d=input("Enter a name followed by the date of birth:")
print(a)
print(b)
print(c)
print(d)
print(e)